### ISSUE TITLE
Must delete bin/*/*.pyc (etc) on uninstall or upgrade

### ISSUE THREAD

**Issue by marbx** [marbx/salt-windows-msi#2]
During runtime,
 - Python writes files (*.pyc) in the program directory.
 - Salt write files in INSTALLDIR.

WiX does not know or assume that, so has to be told.
An msi does not remove file, unless the msi has created them.
I need to specify that bin must be removed recusivly.

RemoveFolderEx
https://www.hass.de/content/wix-how-use-removefolderex-your-xml-scripts
http://stackoverflow.com/questions/195919/removing-files-when-uninstalling-wix

CustomAction ExeCommand
http://stackoverflow.com/questions/17288914/wix-v3-7-how-to-remove-file-in-uninstall-that-was-created-after-installation

**Comment by markuskramerIgitt** [comment]
I assume the *.pyc files are generated after the install.
msi does not remove file, unless the msi has created them.

I need to specify that bin must be removed recusivly.

Uninstall takes roughly one minute and should go much faster.
I should find the reason why it takes a minute.
Maybe because all files are keypath=yes components.

**Comment by markuskramerIgitt** [comment]
`RemoveFolderEx`
http://stackoverflow.com/questions/195919/removing-files-when-uninstalling-wix

`CustomAction ExeCommand`
http://stackoverflow.com/questions/17288914/wix-v3-7-how-to-remove-file-in-uninstall-that-was-created-after-installation
